@baseUrl = http://localhost:5000
@contentType = application/json

@followId = 4ba10488-13b6-407e-b950-2e35b9b07cd1

### ユーザー登録
# @name register
POST {{baseUrl}}/auth/register
Content-Type: {{contentType}}

{
    "email": "test@example.com",
    "password": "password123",
    "name": "testuser"
}

### ユーザIDを環境変数として保存
@userId = {{register.response.body.user_id}}

### ログイン
# @name login
POST {{baseUrl}}/auth/login
Content-Type: {{contentType}}

{
    "email": "test@example.com",
    "password": "password123"
}

### トークンを環境変数として保存
@authToken = {{login.response.body.token}}


### ユーザプロフィールの取得
GET {{baseUrl}}/users/{{userId}}
Authorization: Bearer {{authToken}}
Content-Type: {{contentType}}

### 全ユーザーの取得
GET {{baseUrl}}/trees
Content-Type: {{contentType}}


### ユーザーの全ツリー取得
GET {{baseUrl}}/users/{{userId}}/trees
Authorization: Bearer {{authToken}}
Content-Type: {{contentType}}

### 新しいツリーを作成
# @name createTree
POST {{baseUrl}}/users/{{userId}}/trees
Authorization: Bearer {{authToken}}
Content-Type: {{contentType}}

{
    "title": "プログラミングの夢",
    "dreams": [
        {
            "title": "プログラミングを学ぶ",
            "position": 1
        },
        {
            "title": "プログラミングを極める",
            "position": 2
        }
    ]
}

### ツリーIDを環境変数として保存
@treeId = {{createTree.response.body.id}}

### 特定のツリーの詳細を取得
GET {{baseUrl}}/users/{{userId}}/trees/{{treeId}}
Authorization: Bearer {{authToken}}
Content-Type: {{contentType}}

### ツリーの情報を更新
PATCH {{baseUrl}}/users/{{userId}}/trees/{{treeId}}
Authorization: Bearer {{authToken}}
Content-Type: {{contentType}}

{
    "name": "Updated Programming Dream",
    "ended_at": "2024-12-31T23:59:59Z"
}

### ツリーを削除
DELETE {{baseUrl}}/users/{{userId}}/trees/{{treeId}}
Authorization: Bearer {{authToken}}
Content-Type: {{contentType}}

### ユーザプロフィールの更新
PATCH {{baseUrl}}/users/{{userId}}
Authorization: Bearer {{authToken}}
Content-Type: {{contentType}}

{
    "email": "updated@example.com",
    "name": "updateduser"
}

### すべてのユーザプロフィールのリストを取得
GET {{baseUrl}}/users
Authorization: Bearer {{authToken}}
Content-Type: {{contentType}}


### フォロー用のユーザー登録
# @name follow-register
POST {{baseUrl}}/auth/register
Content-Type: {{contentType}}

{
    "email": "follow@example.com",
    "password": "follow123",
    "name": "followuser"
}


### ユーザをフォロー
POST {{baseUrl}}/follow/{{followId}}
Authorization: Bearer {{authToken}}
Content-Type: {{contentType}}


### ユーザのフォローを解除
DELETE  {{baseUrl}}/follow/{{followId}}
Authorization: Bearer {{authToken}}
Content-Type: {{contentType}}


### ユーザのことをフォローしているユーザのリストを取得する
GET {{baseUrl}}/follow/{{userId}}/followers
Authorization: Bearer {{authToken}}
Content-Type: {{contentType}}


### ユーザがフォローしているユーザのリストを取得する
GET {{baseUrl}}/follow/{{userId}}/following
Authorization: Bearer {{authToken}}
Content-Type: {{contentType}}
