@baseUrl = http://localhost:5000
@contentType = application/json

@userId = bba4eb2e-25bc-4e6a-8cd9-e20571d2afd1

### ユーザー登録
POST {{baseUrl}}/auth/register
Content-Type: {{contentType}}

{
    "email": "test@example.com",
    "password": "password123",
    "name": "testuser"
}

### ログイン
# @name login
POST {{baseUrl}}/auth/login
Content-Type: {{contentType}}

{
    "email": "test@example.com",
    "password": "password123"
}

### トークンを環境変数として保存
@authToken = {{login.response.body.token}}

### ツリー作成
POST {{baseUrl}}/trees/{{userId}}
Authorization: Bearer {{authToken}}
Content-Type: {{contentType}}

{
    "title": "My First Dream Tree",
    "dreams": [
        {
            "title": "Learn Programming",
            "position": 1
        }
    ]
}

### ユーザプロフィールの取得
GET {{baseUrl}}/users/{{userId}}
Authorization: Bearer {{authToken}}
Content-Type: {{contentType}}


### ユーザプロフィールの更新
PATCH {{baseUrl}}/users/{{userId}}
Authorization: Bearer {{authToken}}
Content-Type: {{contentType}}

{
    "email": "updated@example.com",
    "name": "updateduser"
}


### すべてのユーザプロフィールのリストを取得
GET {{baseUrl}}/users
Authorization: Bearer {{authToken}}
Content-Type: {{contentType}}