services:
  prism:
    image: stoplight/prism:4
    command: "mock -h 0.0.0.0 /tmp/api.oas3.yml"
    volumes:
      - ../docs/openapi.yaml:/tmp/api.oas3.yml:ro
    ports:
      # Serve the mocked API locally as available on port 5000
      - "5000:4010"
