openapi: 3.0.0
info:
  title: Dream Tree API
  version: 1.0.0
tags:
  - name: auth
    description: User authentication
  - name: tree
    description: User tree management
  - name: user
    description: User profile management
  - name: follow
    description: User follow management
paths:
  /auth/register:
    post:
      tags:
        - auth
      summary: 新しいユーザアカウントを登録する
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
                username:
                  type: string
      responses:
        201:
          description: User registered successfully
  
  /auth/login:
    post:
      tags:
        - auth
      summary: ユーザを認証してログインする
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        200:
          description: User logged in successfully
  
  /auth/reset-password:
    post:
      tags:
        - auth
      summary: ユーザのメールにパスワードリセットリンクを送信する
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
      responses:
        200:
          description: Password reset link sent successfully
  
  /trees/{user_id}:
    get:
      tags:
        - tree
      summary: ユーザが作成したツリーのリストを取得する
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: List of user's trees retrieved successfully
    post:
      tags:
        - tree
      summary: ユーザが新しいツリーを作成する
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                dreams:
                  type: array
                  items:
                    properties:
                      id:
                        type: string
                      title:
                        type: string
                      tree_id:
                        type: integer
                      created_at:
                        type: string
                      ended_at:
                        type: string
      responses:
        201:
          description: New tree created successfully
  
  /trees/{user_id}/{id}:
    get:
      tags:
        - tree
      summary: ユーザが作成した特定のツリーの詳細を取得する
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Tree details retrieved successfully
    patch:
      tags:
        - tree
      summary: ユーザが作成したツリーのステータスを更新する
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                ended_at:
                  type: string
      responses:
        200:
          description: Tree status updated successfully
    delete:
      tags:
        - tree
      summary: ユーザが作成した特定のツリーを削除する
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Tree deleted successfully
  
  /trees:
    get:
      tags:
        - tree
      summary: 全ユーザが作成したすべてのツリーのリストを取得する
      responses:
        200:
          description: List of all trees retrieved successfully

  /users/{id}:
    get:
      tags:
        - user
      summary: ユーザプロフィールの詳細を取得する
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: User profile retrieved successfully
    patch:
      tags:
        - user
      summary: ユーザプロフィール情報を更新する
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                name:
                  type: string
      responses:
        200:
          description: User profile updated successfully
  
  /users:
    get:
      tags:
        - user
      summary: すべてのユーザプロフィールのリストを取得する
      responses:
        200:
          description: List of all user profiles retrieved successfully
  
  
  /follow:
    post:
      tags:
        - follow
      summary: ユーザをフォローする
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                from_user_id:
                  type: string
                to_user_id:
                  type: string
      responses:
        201:
          description: Follow created successfully

  /unfollow:
    post:
      tags:
        - follow
      summary: ユーザのフォローを解除する
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                from_user_id:
                  type: string
                to_user_id:
                  type: string
      responses:
        200:
          description: Unfollowed successfully

  /followers/{user_id}:
    get:
      tags:
        - follow
      summary: ユーザのことをフォローしているユーザのリストを取得する
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: List of followers retrieved successfully

  /following/{user_id}:
    get:
      tags:
        - follow
      summary: ユーザがフォローしているユーザのリストを取得する
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: List of following retrieved successfully