openapi: 3.0.0
info:
  title: Dream Tree API
  version: 1.0.0
tags:
  - name: auth
    description: User authentication
  - name: tree
    description: User tree management
  - name: share
    description: Dream sharing and SNS integration
  - name: user
    description: User profile management
paths:
  /auth/register:
    post:
      tags:
        - auth
      summary: 新しいユーザーアカウントを登録する
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
                username:
                  type: string
      responses:
        201:
          description: User registered successfully
  
  /auth/login:
    post:
      tags:
        - auth
      summary: ユーザーを認証してログインする
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        200:
          description: User logged in successfully
  
  /auth/reset-password:
    post:
      tags:
        - auth
      summary: ユーザーのメールにパスワードリセットリンクを送信する
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
      responses:
        200:
          description: Password reset link sent successfully
  
  /trees/{user_id}:
    get:
      tags:
        - tree
      summary: ユーザーが作成したツリーのリストを取得する
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: List of user's trees retrieved successfully
    post:
      tags:
        - tree
      summary: ユーザーのために新しいツリーを作成する
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
      responses:
        201:
          description: New tree created successfully
  
  /trees/{id}:
    get:
      tags:
        - tree
      summary: 特定のツリーの詳細を取得する
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Tree details retrieved successfully
    patch:
      tags:
        - tree
      summary: ツリーのステータスを更新する
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
      responses:
        200:
          description: Tree status updated successfully
    delete:
      tags:
        - tree
      summary: 特定のツリーを削除する
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Tree deleted successfully
  
  /trees:
    get:
      tags:
        - tree
      summary: ユーザーが作成したすべてのツリーのリストを取得する
      responses:
        200:
          description: List of all trees retrieved successfully

  /share:
    post:
      tags:
        - share
      summary: 夢をソーシャルメディアで共有する
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                dreamId:
                  type: string
                event:
                  type: string
                  enum: [created, achieved]
      responses:
        200:
          description: Dream shared successfully
  
  /profiles/{id}:
    get:
      tags:
        - user
      summary: ユーザープロフィールの詳細を取得する
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: User profile retrieved successfully
    patch:
      tags:
        - user
      summary: ユーザープロフィール情報を更新する
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                age:
                  type: integer
                profession:
                  type: string
      responses:
        200:
          description: User profile updated successfully
  
  /profiles:
    get:
      tags:
        - user
      summary: すべてのユーザープロフィールのリストを取得する
      responses:
        200:
          description: List of all user profiles retrieved successfully